# Generated by Django 5.0.7 on 2025-02-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
